const s = '@vue/reactivity',
  t = '3.2.31',
  e = '@vue/reactivity',
  i = 'index.js',
  r = 'dist/reactivity.esm-bundler.js',
  d = 'dist/reactivity.d.ts',
  a = 'dist/reactivity.global.js',
  o = 'dist/reactivity.global.js',
  c = [
    'LICENSE',
    'README.md',
    'dist/reactivity.cjs.prod.js',
    'dist/reactivity.cjs.prod.js.map',
    'dist/reactivity.esm-browser.js',
    'dist/reactivity.esm-browser.js.map',
    'dist/reactivity.esm-browser.prod.js',
    'dist/reactivity.esm-browser.prod.js.map',
    'dist/reactivity.esm-bundler.js',
    'dist/reactivity.esm-bundler.js.map',
    'dist/reactivity.global.js',
    'dist/reactivity.global.js.map',
    'dist/reactivity.global.prod.js',
    'dist/reactivity.global.prod.js.map',
    'index.js',
    'index.js.map',
    'package.json',
    'package.json.js',
    'package.json.js.map',
  ],
  w = !1,
  j = {
    type: 'git',
    url: 'git+https://github.com/vuejs/core.git',
    directory: 'packages/reactivity',
  },
  n = {
    name: 'VueReactivity',
    formats: ['esm-bundler', 'esm-browser', 'cjs', 'global'],
  },
  v = ['vue'],
  p = 'Evan You',
  l = 'MIT',
  y = { url: 'https://github.com/vuejs/core/issues' },
  m = 'https://github.com/vuejs/core/tree/main/packages/reactivity#readme',
  b = { '@vue/shared': '3.2.31' },
  u = {
    '.': {
      module: './dist/reactivity.esm-bundler.js',
      default: { development: './index.js', default: './index.js' },
    },
    './index.js': { development: './index.js', default: './index.js' },
    './index': './index.js',
    './dist/reactivity.cjs.prod': './dist/reactivity.cjs.prod.js',
    './dist/reactivity.esm-browser.js': './dist/reactivity.esm-browser.js',
    './dist/reactivity.esm-browser': './dist/reactivity.esm-browser.js',
    './dist/reactivity.esm-browser.prod.js':
      './dist/reactivity.esm-browser.prod.js',
    './dist/reactivity.esm-browser.prod':
      './dist/reactivity.esm-browser.prod.js',
    './dist/reactivity.esm-bundler.js': './dist/reactivity.esm-bundler.js',
    './dist/reactivity.esm-bundler': './dist/reactivity.esm-bundler.js',
    './dist/reactivity.global': './dist/reactivity.global.js',
    './dist/reactivity.global.prod': './dist/reactivity.global.prod.js',
    './package.json': './package.json.js',
    './dist/reactivity.cjs.prod.js!cjs': './dist/reactivity.cjs.prod.js',
    './dist/reactivity.esm-browser.js!cjs': './dist/reactivity.esm-browser.js',
    './dist/reactivity.esm-browser.prod.js!cjs':
      './dist/reactivity.esm-browser.prod.js',
    './dist/reactivity.global.js!cjs': './dist/reactivity.global.js',
    './dist/reactivity.global.prod.js!cjs': './dist/reactivity.global.prod.js',
    './package.json.js!cjs': './package.json.js',
    './index.js!cjs': './index.js',
  },
  g = !0
var x = {
  name: s,
  version: t,
  description: e,
  main: i,
  module: r,
  types: d,
  unpkg: a,
  jsdelivr: o,
  files: c,
  sideEffects: !1,
  repository: j,
  buildOptions: n,
  keywords: v,
  author: p,
  license: l,
  bugs: y,
  homepage: m,
  dependencies: b,
  exports: u,
  __ESMD__: g,
}
export {
  g as __ESMD__,
  p as author,
  y as bugs,
  n as buildOptions,
  x as default,
  b as dependencies,
  e as description,
  u as exports,
  c as files,
  m as homepage,
  o as jsdelivr,
  v as keywords,
  l as license,
  i as main,
  r as module,
  s as name,
  j as repository,
  w as sideEffects,
  d as types,
  a as unpkg,
  t as version,
}
//# sourceMappingURL=package.json.js.map
